'版本 3.1 到 4.1'

'公司信息表添加位置信息'
ALTER TABLE COMPANY_TABLE ADD LOCATION VARCHAR(20);

'管理员信息表添加所有所属公司id'
ALTER TABLE ADMIN_USER ADD COMPANYS VARCHAR(20);

'创建新的一天三班表'
CREATE TABLE  RULE_DAY_RANGE(
	ID INTERGER NOT NULL,
	FATHER INTERGER NOT NULL,
	FATHER_NAME VARCHAR(10),
	LATE_TIME INTERGER,
	LEFTE_EARLY INTERGER,
	OFFWORK_BEGIN VARCHAR(10),
	OFFWORK_END VARCHAR(10),
	OFFWORK_CHECK INTERGER,
	TIME1 VARCHAR(10),
	TIME2 VARCHAR(10),
	WORK_BEGIN VARCHAR(10),
	WORK_END VARCHAR(10),
	WORK_CHECK INTERGER,
	DAYS VARCHAR(10),
	PRIMARY KEY("ID")
);

'创建版本'
CREATE TABLE SERVER_VERSION (
  TITLE_VER  INTERGER NOT NULL,
	MAIN_VER INTERGER NOT NULL
);

'VERIFY_PERSON 添加验证结果'
ALTER TABLE VERIFY_PERSON ADD RESULT VARCHAR(20);
ALTER TABLE VERIFY_PERSON ADD RANGE_INDEX INTERGER;
ALTER TABLE VERIFY_PERSON ADD ATTENDANCE_TIME VARCHAR(10);
ALTER TABLE VERIFY_PERSON ADD DEVICE_NAME VARCHAR(10);
ALTER TABLE VERIFY_PERSON ADD CREATE_DATE VARCHAR(10);


'人员表添加公司ID'
ALTER TABLE EMPLOYEE_INFO ADD COMPANY_ID INTEGER;